# Generated by Django 5.0.3 on 2024-03-24 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_newsmodel_news_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsmodel',
            old_name='news_image',
            new_name='news_images',
        ),
    ]
