# Generated by Django 5.0.3 on 2024-03-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_news_image_newsmodel_news_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='news_images',
            field=models.FileField(upload_to='news_images/'),
        ),
    ]
